# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ecf_re_cpp <- function(t, smp) {
    .Call('_empichar_ecf_re_cpp', PACKAGE = 'empichar', t, smp)
}

ecf_im_cpp <- function(t, smp) {
    .Call('_empichar_ecf_im_cpp', PACKAGE = 'empichar', t, smp)
}

ecf_mod_cpp <- function(t, smp) {
    .Call('_empichar_ecf_mod_cpp', PACKAGE = 'empichar', t, smp)
}

ecf_cpp <- function(t, smp) {
    .Call('_empichar_ecf_cpp', PACKAGE = 'empichar', t, smp)
}

